name: Changelog Updater

on:
  schedule:
    # Runs every 4 hours
    - cron: '0 */4 * * *'
  push:
    branches:
      - main

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install Doppler
        uses: dopplerhq/cli-action@v2

      - name: Install dependencies
        run: npm ci

      - name: Generate Changelog
        run: npm run generate-changelog
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}

      - name: Commit Changelog
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add ./public/changelogs
          git commit -m "Update Changelog" || echo "No changes to commit"
          git push
